Add validation for workflow of cairo lint

diff --git a/.github/workflows/website-deploy.yml b/.github/workflows/website-deploy.yml
--- a/.github/workflows/website-deploy.yml
+++ b/.github/workflows/website-deploy.yml
@@ -25,9 +25,25 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  validate-branch:
+    name: Validate target branch
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set target ref
+        run: |
+          # The regex for 'v[0-9]+.[0-9]+.[0-9]+'
+          VERSION_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+$"
+          INPUT_BRANCH="${{ inputs.target_branch }}"
+
+          # If the branch does not match the version regex, exit with failure.
+          if [[ ! $INPUT_BRANCH =~ $VERSION_REGEX ]]; then
+            exit 1
+          fi
   build:
     name: Build website
     runs-on: ubuntu-latest
+    needs:
+      - validate-branch
     defaults:
       run:
         working-directory: ./website
@@ -58,7 +74,9 @@ jobs:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
-    needs: build
+    needs:
+      - validate-branch
+      - build
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
